package graphics;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;


/**
 * Descripiton
 *
 * @author Yotam
 * @version $VERSION 30/04/2017
 * @see
 */
public class ZooFrame extends JFrame {

    private JMenuBar menuBar;
    private JMenu fileMenu, backgroundMenu, helpMenu;
    private JMenuItem exitMenuI, imageMenuI, greenMenuI, noneMenuI, helpMenuI;
    private ZooPanel zooPanel;
    private JPanel panel1;
    private Color bgGreen;
    private Image bgImage;

    public ZooFrame(String name) {
        super(name);
        bgGreen = new Color(124, 201, 61);
        try {
            bgImage = ImageIO.read(new File("src\\graphics\\pictures\\savanna.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setSize(1080, 720);
        menuInit();
    }

    public void menuInit() {
        menuBar = new JMenuBar();
        zooPanel = new ZooPanel(this);
        add(zooPanel);
        buildFileMenu();
        buildBackgroundMenu();
        buildHelpMenu();
        setVisible(true);
    }

    public ActionListener help1ActionListener() {
        ActionListener AL = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "Home Work 3\nGui @ Threads");
            }
        };
        return AL;
    }

    public void buildHelpMenu() {
        //Build the Help menu
        helpMenu = new JMenu("Help");
        helpMenu.setMnemonic(KeyEvent.VK_A);
        menuBar.add(helpMenu);
        helpMenuI = new JMenuItem("Help");
        helpMenuI.addActionListener(help1ActionListener());
        helpMenu.add(helpMenuI);
        menuBar.add(helpMenu);
        setJMenuBar(menuBar);
    }

    private ActionListener greenActionListener() {
        ActionListener AL = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                zooPanel.setBackgroundColor(bgGreen);
            }
        };
        return AL;
    }

    private ActionListener noneActionListener() {
        ActionListener AL = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                zooPanel.setBackgroundColor(getBackground());
            }
        };
        return AL;
    }

    private ActionListener imageActionListener() {
        ActionListener AL = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                zooPanel.setBackgroundImage(bgImage);
            }
        };
        return AL;
    }

    public void buildBackgroundMenu() {
        //Build the Background menu
        backgroundMenu = new JMenu("Background");
        backgroundMenu.setMnemonic(KeyEvent.VK_A);
        menuBar.add(backgroundMenu);
        imageMenuI = new JMenuItem("Image");
        imageMenuI.addActionListener(imageActionListener());
        greenMenuI = new JMenuItem("Green");
        greenMenuI.addActionListener(greenActionListener());
        noneMenuI = new JMenuItem("None");
        noneMenuI.addActionListener(noneActionListener());
        backgroundMenu.add(imageMenuI);
        backgroundMenu.addSeparator();
        backgroundMenu.add(greenMenuI);
        backgroundMenu.addSeparator();
        backgroundMenu.add(noneMenuI);
        menuBar.add(backgroundMenu);
    }


    public ActionListener exitActionListener() {
        ActionListener AL = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        };
        return AL;
    }

    public void buildFileMenu() {
        //Build the File menu
        fileMenu = new JMenu("File");
        fileMenu.setMnemonic(KeyEvent.VK_A);
        exitMenuI = new JMenuItem("Exit");//creating the Exit menu item
        exitMenuI.addActionListener(exitActionListener());
        fileMenu.add(exitMenuI);//adding it
        menuBar.add(fileMenu);
    }

    public static void main(String[] args) {
        ZooFrame zooFrame = new ZooFrame("Zoo");
        zooFrame.setLocationRelativeTo(null);
//        AddAnimalDialog addAnimal = new AddAnimalDialog("Add an Animal Dialog");
//        addAnimal.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
