package graphics;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 * Descripiton
 *
 * @author Yotam
 * @version $VERSION 30/04/2017
 * @see
 */
public class ZooPanel extends JPanel implements Runnable {

    private JButton addAnimalZP;
    private JButton sleepZP;
    private JButton wakeUpZP;
    private JButton clearZP;
    private JButton foodZP;
    private JButton infoZP;
    private JButton exitZP;


    public ZooPanel() {
        addAnimalZP = new JButton("Add Animal");
        sleepZP = new JButton("Sleep");
        wakeUpZP = new JButton("Wake up");
        clearZP = new JButton("Clear All");
        foodZP = new JButton("Food ");
        infoZP = new JButton("Info");
        exitZP = new JButton("Exit");
    }

    public void init() {
        addAnimalZP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AddAnimal addAnimal = new AddAnimal("Add an Animal Dialog");
            }
        });

//        infoZP.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                JTable animalJTabel = new JTable();
//                String[] columnNames = {"Animal", "Color", "Weight", "Hor. Speed", "Ver. Speed", "Eat Counter"};
//                String[][] data;
//            }
//        });
//
//        foodZP.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                Object[] choices = {"Meat", "Cabbage", "Lettuce"};
//                int choice = JOptionPane.showOptionDialog(null, "Please Choose Food", "Food for Animals",
//                        JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
//                        null, choices, choices[0]);
//                if (choice == 0) {
//                    System.out.println("Meat");
////                    ImageIcon meatIcon = new ImageIcon("meat.gif");
////                    JLabel meatLabel = new JLabel();
////                    meatLabel.setIcon(meatIcon);
////                    meatLabel.setVisible(true);
////                    getconadd(meatLabel);
//                    BufferedImage meatIcon = ImageIO.read("C:\Users\Yotam\Ex3\src\graphics\pictures\meat.gif");//it must be an image file, otherwise you'll get an exception
//                    JLabel meatLabel = new JLabel();
//                    meatLabel.setIcon(new ImageIcon(meatIcon));
//                    getContentPane().add(meatLabel);
//                }
//
//
//            }
//        });


        add(addAnimalZP);
        add(sleepZP);
        add(wakeUpZP);
        add(clearZP);
        add(foodZP);
        add(infoZP);
        add(exitZP);
    }


    /**
     * When an object implementing interface <code>Runnable</code> is used
     * to create a thread, starting the thread causes the object's
     * <code>run</code> method to be called in that separately executing
     * thread.
     * <p>
     * The general contract of the method <code>run</code> is that it may
     * take any action whatsoever.
     *
     * @see Thread#run()
     */
    @Override
    public void run() {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        panel1.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }
}
